# Generated by Django 6.0.3 on 2026-06-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0007_alter_pais_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='status',
            field=models.CharField(blank=True, choices=[('Visitei', 'VISITEI'), ('PRETENDO IR', 'Pretendo Ir'), ('Não Pretendo Ir', 'NAO PRETENDO IR'), ('NAO ADICIONADO', 'Não Adicionado')], default='Não Adicionado', max_length=20, null=True),
        ),
    ]
