# Generated by Django 6.0.3 on 2026-06-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0008_alter_pais_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='esportes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='localizacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='pratoTipico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='status',
            field=models.CharField(blank=True, choices=[('Visitei', 'VISITEI'), ('Pretendo Ir', 'PRETENDO IR'), ('Não Pretendo Ir', 'NAO PRETENDO IR'), ('NAO ADICIONADO', 'Não Adicionado')], default='Não Adicionado', max_length=20, null=True),
        ),
    ]
